# Generated by Django 6.0.1 on 2026-01-14 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phone", models.CharField(max_length=20)),
                ("identity", models.CharField(blank=True, max_length=30, null=True)),
                ("age", models.IntegerField()),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("YOUTH", "YOUTH"),
                            ("PRIME", "PRIME"),
                            ("MIDDLE", "MIDDLE"),
                            ("SENIOR", "SENIOR"),
                        ],
                        max_length=10,
                    ),
                ),
                ("weight", models.FloatField()),
                ("height", models.FloatField()),
                ("ills", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PostureRecord",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (0, "LIE"),
                            (1, "STAND"),
                            (2, "SIT"),
                            (3, "WALK"),
                            (4, "RUN"),
                        ]
                    ),
                ),
                ("lumbar_stable_angle", models.FloatField()),
                ("trunk_stable_angle", models.FloatField()),
                (
                    "posture_risk_level",
                    models.CharField(
                        choices=[
                            ("NORMAL", "NORMAL"),
                            ("MILD_RISK", "MILD_RISK"),
                            ("SEVERE_RISK", "SEVERE_RISK"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("YOUTH", "YOUTH"),
                            ("PRIME", "PRIME"),
                            ("MIDDLE", "MIDDLE"),
                            ("SENIOR", "SENIOR"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ills", models.TextField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="posture.user"
                    ),
                ),
            ],
        ),
    ]
