# Generated by Django 4.2.15 on 2026-01-19 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posture", "0003_alter_user_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posturerecord",
            name="age_group",
        ),
        migrations.RemoveField(
            model_name="posturerecord",
            name="ills",
        ),
        migrations.RemoveField(
            model_name="posturerecord",
            name="lumbar_stable_angle",
        ),
    ]
