# Generated by Django 4.2.15 on 2026-03-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posture", "0004_remove_posturerecord_age_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("posture_analysis", models.TextField(blank=True, null=True)),
                ("health_analysis", models.TextField(blank=True, null=True)),
                ("activity_analysis", models.TextField(blank=True, null=True)),
                ("plan_basis", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="posture.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("day", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("intensity", models.CharField(max_length=20)),
                ("duration", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("diet", models.TextField(blank=True, null=True)),
                ("rest", models.TextField(blank=True, null=True)),
                (
                    "training_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="posture.trainingplan",
                    ),
                ),
            ],
        ),
    ]
