# Generated by Django 4.2.15 on 2026-03-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posture", "0005_trainingplan_exercise"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingplan",
            name="user",
        ),
        migrations.DeleteModel(
            name="Exercise",
        ),
        migrations.DeleteModel(
            name="TrainingPlan",
        ),
    ]
