# Generated by Django 4.2.15 on 2026-04-03 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posture", "0006_remove_trainingplan_user_delete_exercise_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("posture_analysis", models.TextField(blank=True, null=True)),
                ("health_analysis", models.TextField(blank=True, null=True)),
                ("activity_analysis", models.TextField(blank=True, null=True)),
                ("plan_basis", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_plans",
                        to="posture.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("day", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=200)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("intensity", models.CharField(max_length=50)),
                ("duration", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("diet", models.TextField(blank=True, null=True)),
                ("rest", models.TextField(blank=True, null=True)),
                (
                    "training_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="posture.trainingplan",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
    ]
